services:
  # Backend API Service
  - type: web
    name: finanzas-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      # Database Configuration (usar tu Supabase existente)
      - key: DB_HOST
        value: aws-1-sa-east-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres.pcdeqbulxbpspdzemizn
      - key: DB_PASSWORD
        sync: false  # Configurar manualmente en Render Dashboard
      - key: DB_NAME
        value: postgres
      - key: DB_SSLMODE
        value: require

      # Server Configuration
      - key: SERVER_PORT
        value: 8080
      - key: SERVER_HOST
        value: 0.0.0.0

      # Application
      - key: APP_ENV
        value: production

      # JWT Configuration
      - key: JWT_SECRET_KEY
        sync: false  # Configurar manualmente en Render Dashboard (usar un secreto fuerte)
      - key: JWT_ISSUER
        value: finanzas-backend
      - key: JWT_EXPIRATION_HRS
        value: 24

    healthCheckPath: /swagger/index.html
